### PR TITLE
Diberry/0422 v4

### PR DESCRIPTION
**Pull request by diberry**

### CODE REVIEW

**Review by ggailey777 — CHANGES_REQUESTED** [review]
Shoot! It looks like we still have v3 references in at least [one include](https://github.com/MicrosoftDocs/azure-docs-pr/blob/main/includes/functions-add-output-binding-example-all-languages.md?plain=1#L51):

```markdown
### [v3](#tab/node-v3)
:::code language="json" source="~/functions-docs-javascript/functions-add-output-binding-storage-queue-cli/HttpExample/function.json" highlight="18-24" :::
```
Maybe can we leave at least the old `functions-add-output-binding-storage-queue-cli` folder? Merging this would break the next doc build 😨

**Comment by ggailey777** [comment]
These are all the references to that folder, and I think we can remove or swap the others--but I wasn't planning on removing the v3 tab, except for the quickstart(s).

image

**Comment by diberry** [comment]
@ggailey777 One more look? 

Replaced origin folder
Added new v4 folder

**Review by ggailey777 — APPROVED** [review]
Thanks!

**Comment by diberry** [comment]
@ggailey777 I don't have JIT access. Can you merge this?

**Pull request merged**
